### ISSUE TITLE
The updater does not update itself

### ISSUE THREAD

**Issue by Minion3665** [GenElectrovise/VIRPTEQ-Updater#2]
As mentioned in #1, the updater doesn't update itself. This may be a problem as if the updater needs an update it will need to be reinstalled by all users

What did I say?

**Comment by atom-dispencer** [comment]
Thank you @Minion3665 . This issue has already been raised and explained in #1 . This feature will be added at a later date. Please see #1 and that I have already mentioned this as an issue with Release 1

**Comment by Minion3665** [comment]
Generally it's good to create a new issue for each issue so as not to lump them together as it doesn't help to manage your issues, (for example what if one part of the issue was resolved but not the other as? Would the issue be resolved or not?)

@GenElectrovise
